# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20170627_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Styles'),
        ),
        migrations.AlterField(
            model_name='beers_per_style',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Styles'),
        ),
    ]
