# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20170627_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breweries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(max_length=200)),
                ('brand_classification', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('is_organic', models.BooleanField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
