# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0005_auto_20170720_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='breweries',
            name='address',
            field=models.CharField(default='not available yet', max_length=200),
        ),
    ]
